### ISSUE TITLE
Loading base configuration from differents formats : TOML, YAML or from an in-line Rust builder pattern

### ISSUE THREAD

**Issue by Esgr0bar** [Memoscopy/libMMU#4]
we'll use this logic https://rust-unofficial.github.io/patterns/patterns/creational/builder.html
- [x] handle YAML (done ->need to be tested)
- [x] handle TOML  (done ->need to be tested)
- [x] handle in-line
- [x] handle JSON
- [x] handle XML  (done ->need to be tested)
- [x] find which type of file is passed

Maybe we finally use only in-line format or one format and stick with it

**Comment by shard77** [comment]
@Esgr0bar I don't think there's any need to handle XML/JSON/YAML.
I think it's better if we stick to one specific format.

**Comment by Esgr0bar** [comment]
@shard77 no problem that doesn't change a lot the code we can stick to one format.
Here's the code that handle the different format :
```rust
fn load_config(file_path: &str) -> Result<MachineConfig, Box<dyn Error>> {
    let config_str = fs::read_to_string(file_path)?;
    let config: MachineConfig = match file_path.rsplit('.').next().ok_or("No file extension found")? {
        "json" => serde_json::from_str(&config_str)?,
        "yaml" => serde_yaml::from_str(&config_str)?,
        "toml" => toml::from_str(&config_str)?,
        "xml" => serde_xml_rs::from_str(&config_str)?,
        _ => return Err("Unsupported file format".into()),
    };
    Ok(config)
}
```

**Comment by shard77** [comment]
> @shard77 no problem that doesn't change a lot the code we can stick to one format. Here's the code that handle the different format :
> 
> ```rust
> fn load_config(file_path: &str) -> Result<MachineConfig, Box<dyn Error>> {
>     let config_str = fs::read_to_string(file_path)?;
>     let config: MachineConfig = match file_path.rsplit('.').next().ok_or("No file extension found")? {
>         "json" => serde_json::from_str(&config_str)?,
>         "yaml" => serde_yaml::from_str(&config_str)?,
>         "toml" => toml::from_str(&config_str)?,
>         "xml" => serde_xml_rs::from_str(&config_str)?,
>         _ => return Err("Unsupported file format".into()),
>     };
>     Ok(config)
> }
> ```

alright, perfect :+1: 
@Esgr0bar Did you use the derive feature from serde?

**Comment by Esgr0bar** [comment]
@shard77 Yeah, you can look my code it is push in the branch
